########################### Default configuration ######################
baseURL = "https://www.opsta.co.th/"
title = "Opsta | DevSecOps Platform Engineering Specialist"
theme = "opsta-www.github.io"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
# disqusShortname = "opsta" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here

[outputs]
home = ["HTML", "RSS", "JSON"]
  
############################### Plugins #################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/fontawesome/fontawesome.all.min.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"

########################### navigation ################################
# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Products"
URL = "about"
weight = 2

[[menu.main]]
name = "Opstella Self-Hosted"
URL = "https://www.opstella.com"
parent = "Products"

# join us
[[menu.careers]]
name = "Join Us"
URL = "/career/"
weight = 4

# footer menu
[[menu.footer]]
name = "Solutions & Services"
URL = "service"
weight = 1
hasChildren = true

[[menu.footer]]
name = "About"
URL = "about"
weight = 2

[[menu.footer]]
name = "Contact"
URL = "contact"
weight = 3

# join us
[[menu.footer]]
name = "Join us"
URL = "https://forms.gle/x4db1yyXm9YEAsu9A"
weight = 4

########################### Default parameters ######################
[params]
logo = "images/opsta-logo.svg"
logo_footer = "images/opsta-logo-white.png"
# top header
top_header = true
# Prefix title
title_prefix = "Opsta | DevSecOps Platform Engineering Specialist"
# Meta data
description = "We are the Enterprise Open Source Technical Consultant & Implementation Team that focuses on DevSecOps Transformation with our experienced professional teams to build a high availability and scalable platform. We specialize in these technologies to transform your organization into a DevSecOps Culture. Our product, Opstella, is also an Internal Developer Portal (IDP) designed to simplify the development process and operations. It accelerates and scales applications quickly, ensuring standard security compliance. With Opstella, you can significantly reduce costs by centralizing and optimizing DevSecOps and Platform Engineering practices."
author = "Opsta"
# contact info
company_name = "Opsta (Thailand) Co.,Ltd."
tax_id = "0105559166030"
address = "220/8 Soi Ladprao 1, Chomphon, Chatuchak, Bangkok, 10900, Thailand"
mobile = "+66611234089"
email = "contact@opsta.co.th"
fb_msg_url = "https://m.me/opstathailand"
line_oa = "@opsta"
line_url = "https://line.me/ti/p/%40opsta"
gmap_url = "https://goo.gl/maps/qRwgWptkpsSRCJiH8"
# contact form action
contact_form_action = "https://formspree.io/mbjzndjn" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-130152-29" # your id
# page sidebar quick contact form
quick_contact = true
# search
search = true
# services menu
menu_services = true

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "contact us"
link = "contact"

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://opsta.us15.list-manage.com/subscribe/post?u=1d18418b2208ab98c441ec4a4&amp;id=fe31049965" # replace this url with yours
mailchimp_form_name = "opsta_subscription" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyA2Gs21l6RN2uAQryeYtWoDN_JcvAQcFgA"
map_latitude = "13.8113858"
map_longitude = "100.5670806"
map_marker = "images/marker.png"

########################### social icon ############################
[[params.social]]
icon = "fa-facebook"
link = "https://fb.me/opstathailand"

[[params.social]]
icon = "fa-facebook"
link = "https://fb.me/opstacareer"

[[params.social]]
icon = "fa-linkedin"
link = "https://linkedin.com/company/opsta"

[[params.social]]
icon = "fa-line"
link = "https://line.me/ti/p/%40opsta"

[[params.social]]
icon = "fa-github"
link = "https://github.com/opsta"

# [[params.social]]
# icon = "fa-twitter"
# link = "https://twitter.com/opstacloud"

# [[params.social]]
# icon = "fa-instagram"
# link = "https://instagram.com/themefisher"

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Copyright &copy; 2024 Opsta (Thailand) Co.,Ltd."
[Languages.en.params]
home = "Home"
# footer content
footer_content = "We provides Enterprise DevSecOps Platform Engineering as a Service with our Enterprise CNCF Open Source Technical Consultant and Implementation Team to transform your organization to DevSecOps culture."

################################### Thai language #####################################
# [Languages.th]
# languageName = "Th"
# languageCode = "th-th"
# contentDir = "content/thai"
# weight = 2
# home = "หน้าหลัก"
# # footer content
# footer_content = "Opsta | DevSecOps Platform Engineering Specialist"
# # copyright
# copyright = "Copyright &copy; 2024 Opsta (Thailand) Co.,Ltd."
